file(STRINGS "${CMAKE_CURRENT_LIST_DIR}/../../manifest.txt" manifest)
foreach(key_value ${manifest})
    string(REGEX MATCH "^[^=]+" key ${key_value})
    string(REPLACE "${key}=" "" value ${key_value})
    set("cross_${key}" "${value}")
endforeach()
